config/routes.rb
Rails.application.routes.draw do
  resources :posts do
    resources :comments, only: [:new, :create]
  end
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "posts#index"

  get 'users/:id/all_posts', to: "posts#all_posts"
  # resources :comments, only: [:new, :create]
  # get 'comments/new', to: "comments#new"
  # post '/comments', to: "comments#create"
  get '/about', to: "posts#about"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post

  validates :username, presence: true
  validates :body, presence: true
  # validates :comments, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  paginates_per 7
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :avatar
  has_many :posts, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :avatar])
      devise_parameter_sanitizer.permit(:account_update, keys: [:username, :avatar])
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    # render 'posts/show'
  end
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    redirect_to post_path(@post)
  end

  private
    def comment_params
      params.require(:comment).permit(:body, :username, :user_id)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, :current_user, except: [:index, :show, :about, :all_posts]

  # GET /posts
  # GET /posts.json
  def index
    # @posts = Post.all.order("created_at DESC").page params[:page]
    @posts = Post.all.order("created_at DESC").page params[:page]
    @user = current_user
    @all = false
  end

  def all_posts
    # @posts = User.where(id: params[:id]).take.posts.all.order("created_at DESC").page params[:page]
    @posts = User.where(id: params[:id]).take.posts.all.order("created_at DESC").page params[:page]
    @all = true
    render "index"
  end

  def about
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @comment = @post.comments.new
    @comments = @post.comments.all
  end

  # GET /posts/new
  def new
    @post = current_user.posts.new
  end

  # GET /posts/1/edit
  def edit
    if user_signed_in? && @post.user_id == current_user.id
    else
      redirect_to root_path
    end
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myblog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">G-Blog</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <!-- <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li> -->
            <li><%= link_to "About", about_path %></li>
            <!-- <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="#">Action</a></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li role="separator" class="divider"></li>
                <li><a href="#">Separated link</a></li>
                <li role="separator" class="divider"></li>
                <li><a href="#">One more separated link</a></li>
              </ul>
            </li> -->
          </ul>
          <!-- <form class="navbar-form navbar-left">
            <div class="form-group">
              <input type="text" class="form-control" placeholder="Search">
            </div>
            <button type="submit" class="btn btn-default">Submit</button>
          </form> -->
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> 
                    <% if current_user.avatar.attached? %>
                      <%= image_tag url_for(current_user.avatar), height: 30, width: 30, class: "img-rounded" %>
                    <% else %>
                      <%= image_tag gravatar_image_url(current_user.email, size: 30), height: 30, width: 30, class: "img-rounded" %>
                    <% end %>
                    <%= current_user.username %> <span class="caret"></span></a>
                  <ul class="dropdown-menu">
                    <!-- <li><a href="#">Action</a></li> -->
                    <!-- <li><a href="#">Another action</a></li> -->
                    <!-- <li><a href="#">Something else here</a></li> -->
                    <li><%= link_to 'New Post', new_post_path, class: "text-success" %></li>
                    <li><%= link_to "Edit Profile", edit_user_registration_path, method: :get %></li>
                    <li role="separator" class="divider"></li>
                    <!-- <li><a href="#">Separated link</a></li> -->
                    <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
                  </ul>
                </li>
            <% else %>
              <li><%= link_to "Login", new_user_session_path, method: :get %></li>
            <% end %>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
    <div class="container">
      <div class="row">
        <% if notice %> 
          <% if notice.include? "success" %>
            <div class="alert alert-success"><%= notice %></div>
          <% else %>
            <div class="alert alert-info"><%= notice %></div>
          <% end %>
        <% end %>
        <%= yield %>
        <div class="col-md-4">
          <div class="content-section">
            <h3>Our Sidebar</h3>
            <p class='text-muted'>You can put any information here you'd like.
              <ul class="list-group">
                  <li class="list-group-item list-group-item-light">Latest Posts</li>
                  <li class="list-group-item list-group-item-light">Announcements</li>
                  <li class="list-group-item list-group-item-light">Calendars</li>
                  <li class="list-group-item list-group-item-light">About</li>
              </ul>
            </p>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :body %>
    <%= form.text_area :body, class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit :class => "btn btn-primary btn-block" %>
  </div>
<% end %>

app/views/posts/about.html.erb
<%= content_tag :div, class: "col-md-8" do %>
  <h3>Hi, I'm Guhan,</h3>
  <p>
    I am the creator of g-blog. I used CoreyMSchafer's flaskblog project's css.
    Hope you like it 
  </p>
<% end %>

app/views/posts/edit.html.erb
<!-- <h1>Editing Post</h1> -->
<div class="col-md-8">

<div class="well myform" style="background-color: white;">
  <fieldset>
    <legend>Editing Post</legend>
    <%= render 'form', post: @post %>
  </fieldset>
</div>

  <%= link_to 'Show', @post, class: "btn btn-warning" %> |
  <%= link_to 'Back', posts_path, class: "btn btn-info" %>

</div>

<script type="text/javascript">
  const tx = document.getElementsByTagName("textarea");
  const txHeight = tx.height;
  for (let i = 0; i < tx.length; i++) {
    if (tx[i].value == '') {
      tx[i].setAttribute("style", "height:" + txHeight + "px;overflow-y:hidden;");
    } else {
      tx[i].setAttribute("style", "height:" + (tx[i].scrollHeight) + "px;overflow-y:hidden;");
    }
    tx[i].addEventListener("input", OnInput, false);
  }

  function OnInput(e) {
    this.style.height = "auto";
    this.style.height = (this.scrollHeight) + "px";
  }
</script>

app/views/posts/index.html.erb
<%= content_tag :div, class: "col-md-8" do %>
  <% if @all %>
   <h2>Posts by <%= @posts.first.user.username %> (<%= @posts.length %>)</h2>
  <% end %>
  <% @posts.each do |post| %>
    <%= content_tag :article, class: "media content-section" do %>
      <% if post.user.avatar.attached? %>
        <%= image_tag url_for(post.user.avatar), class: "img-circle article-img" %>
      <% else %>
        <%= image_tag gravatar_image_url("test@example.com"), class: "img-circle article-img" %>
      <% end %>
      <%= content_tag :div, class: "media-body" do %>
        <%= content_tag :div, class: "article-metadata" do %>
          By <%= link_to "#{ post.user.username }", "users/#{post.user_id}/all_posts", class: "mr-2" %>
          on <small class="text-muted"><%= post.created_at.strftime("%A, %d %B %Y") %></small>
        <% end %>
        <%= content_tag :h2, class: "" do %>
          <%= link_to "#{ post.title.capitalize }", post, class: "article-title" %>
        <% end %>

        <%= content_tag :p, class: "article-content" do %>
          <%= truncate(post.body, length:300) %>
          <span>
          <%= link_to "Read more", post, class: "link" %>
          </span>
        <% end %>
        <%= social_share_button_tag(post.title) %>
      <% end %>
    <% end %>
  <% end %>
  <%= paginate @posts %>
<% end %>

app/views/posts/new.html.erb
<!-- <h1>New Post</h1> -->
<div class="col-md-8">

<div class="well myform" style="background-color: white;">
  <fieldset>
    <legend>New Post</legend>
    <%= render 'form', post: @post %>
  </fieldset>

</div>
<%= link_to 'Back', posts_path, class: "btn btn-info" %>
</div>

<script type="text/javascript">
  const tx = document.getElementsByTagName("textarea");
  const txHeight = tx.height;
  for (let i = 0; i < tx.length; i++) {
    if (tx[i].value == '') {
      tx[i].setAttribute("style", "height:" + txHeight + "px;overflow-y:hidden;");
    } else {
      tx[i].setAttribute("style", "height:" + (tx[i].scrollHeight) + "px;overflow-y:hidden;");
    }
    tx[i].addEventListener("input", OnInput, false);
  }

  function OnInput(e) {
    this.style.height = "auto";
    this.style.height = (this.scrollHeight) + "px";
  }
</script>

app/views/posts/show.html.erb
<%= content_tag :div, class: "col-md-8" do %>
  <center>
    <% if @post.user.avatar.attached? %>
      <%= image_tag url_for(@post.user.avatar), height: 150, width: 150, class: "img-circle" %>
    <% else %>
      <%= image_tag gravatar_image_url("test@example.com", size: 150), class: "img-circle" %>
    <% end %>
  </center>

  <article class="media content-section">
    <h1> <%= @post.title.capitalize %> </h1>
    <hr>
    <div class="media-body">
      <div class="article-metadata">

        <div class="article-content" style="font-size: 17px; font-family: sans-serif;">
          <%= @post.body %>
        </div>
        <br>
        <%= social_share_button_tag(@post.title) %>
        <br>
      </div>
    </div>
    <br><br>
    <% if user_signed_in? && @post.user_id == current_user.id %>
      <%= link_to 'Edit', edit_post_path(@post), class: "btn btn-warning" %> |
      <%= link_to 'Delete', @post, class: "btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %> |
    <% end %>

    <%= link_to 'Back', posts_path, class: "btn btn-primary" %>
  </article>

  <div class="comment-form">
    <% if user_signed_in? %>
      <%= form_for ([@post, @post.comments.build]) do |f| %>
        <div class="form-group">
          <%= f.label "Enter your comment" %>
          <%= f.text_field :body, class: 'form-control' %>
        </div>
        <input type="text" name="comment[username]" id="comment_username" value="<%= current_user.username %>" style="display: none;">
        <input type="number" name="comment[user_id]" id="comment_user_id]" value="<%= current_user.id %>" style="display: none;">
        <%= f.submit 'Submit', class: 'btn btn-primary' %>
      <% end %>
    <% end %>
  </div>

  <h2>Comments (<%= @post.comments.all.length %>)</h2>
  <ul class="comments-list">
    <% @post.comments.all.order("created_at DESC").each do |comment| %>
      <li> 
        <% if User.find(comment.user_id).avatar.attached? %>
          <%= image_tag url_for(User.find(comment.user_id).avatar), height: 30, width: 30, class: "img-rounded" %>
        <% else %>
          <%= image_tag gravatar_image_url("test@example.com", size: 30), height: 30, width: 30, class: "img-rounded" %>
        <% end %>
        <%= comment.body %>
        <p align="right">By <span style="color: red"> <%= comment.username %> </span> commenteed at: <%= comment.created_at.strftime("%A, %d %B %Y") %></p>
        </li>
      <hr>
    <% end %>
  </ul>
  <br><br>
<% end %>